# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 404597907102189034bdf7f2e6cedd07bb3c25ab8ce77dbbd20e1c5e644dff4e18c7c736c0c7fe9f09e789c0cb790fa496faf67dffe882d88bb7573f56cbc9cf

test:
  secret_key_base: b2e757fe940cce8189b5e53b8a79667730b07c28696f8631ff758fa78ba4d71925ec74c7d6c4172b791aaad1149de92485347cb1fe87fd91cff26d353589c2ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
